#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend skhosana.tech
    timeout client  30000
    bind 0:80
    default_backend skhosana.tech_backend

backend skhosana.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 452280-web-01 54.237.120.24:80 check
    server 452280-web-02 100.25.48.203:80 check
EOT

sudo service haproxy restart

